name: "Notify Markdown"
description: "Send markdown notification to notice.yuanzhou.site (type=4)"
inputs:
  url:
    description: "Notification endpoint URL"
    required: false
    default: "https://notice.yuanzhou.site/api/notice"
  type:
    description: "Notification type code"
    required: false
    default: "4"
  title:
    description: "Notification title (e.g., success/failure)"
    required: false
  message:
    description: "Markdown message body; if empty, a default summary will be generated"
    required: false
  repo:
    description: "Repository name"
    required: false
  ref:
    description: "Branch or tag name"
    required: false
  sha:
    description: "Commit SHA"
    required: false
  tags:
    description: "Built image tags"
    required: false
runs:
  using: "composite"
  steps:
    - name: Send notification
      uses: actions/github-script@v7
      with:
        script: |
          const url = core.getInput('url') || 'https://notice.yuanzhou.site/api/notice';
          const type = Number(core.getInput('type') || '4');
          const title = core.getInput('title') || 'unknown';
          const providedMessage = core.getInput('message');
          const repo = core.getInput('repo') || process.env.GITHUB_REPOSITORY;
          const ref = core.getInput('ref') || process.env.GITHUB_REF_NAME;
          const sha = core.getInput('sha') || process.env.GITHUB_SHA;
          const tags = core.getInput('tags') || '';
          const lines = [
            '## 构建完成',
            `- Repo: ${repo}`,
            `- Ref: ${ref}`,
            `- SHA: ${sha}`,
            `- Tags: ${tags}`
          ];
          const message = providedMessage && providedMessage.trim().length > 0 ? providedMessage : lines.join('\n');
          const payload = { message, type, title };
          try {
            const res = await fetch(url, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(payload)
            });
            if (!res.ok) core.warning(`notify failed: ${res.status} ${res.statusText}`);
          } catch (e) {
            core.warning(`notify error: ${e.message}`);
          }
